monit service parsing needs to handle multi-line data (#122)
In some circumstances monit can return multiline data for a
value for a service, such as:

```
Program 'routeCheck'
  status                       Status ok
  monitoring status            Monitored
  monitoring mode              active
  on reboot                    start
  last exit value              255
  last output                  Some routes are not set offloaded in FRR                           but all routes in APPL_DB and ASIC_DB are in sync
                               Failure results: {{
                                   "": {
                                       "missed_FRR_routes": [
                                           {
                                               "destSelected": true,
                                               "distance": 1,
...
```

This results in a parser error like
```
File "/var/AzDevOps/sonic-mgmt/tests/common/utilities.py", line 146, in wait_until
    check_result = condition(*args, **kwargs)
  File "/var/AzDevOps/sonic-mgmt/tests/memory_checker/test_memory_checker.py", line 434, in is_monit_mem_ok
    status = self.get_monit_mem_status()
  File "/var/AzDevOps/sonic-mgmt/tests/memory_checker/test_memory_checker.py", line 431, in get_monit_mem_status
    return get_monit_service_status(self.duthost, self.memory_service_name)
  File "/var/AzDevOps/sonic-mgmt/tests/memory_checker/test_memory_checker.py", line 180, in get_monit_service_status
    services = parse_monit_output(result["stdout_lines"])
  File "/var/AzDevOps/sonic-mgmt/tests/memory_checker/test_memory_checker.py", line 161, in parse_monit_output
    key, value = line.lstrip().split('  ', 1)
ValueError: not enough values to unpack (expected 2, got 1)
, error:not enough values to unpack (expected 2, got 1)
```

This patch adds handling for ignoring multi-line output since
no tests rely on it.

Signed-off-by: Brad House <bhouse@nexthop.ai>