NOS-4921: Fix type errors in test_bgp_router_id.py (#1052)
<!--
Please make sure you've read and understood our contributing guidelines;
https://github.com/sonic-net/SONiC/blob/gh-pages/CONTRIBUTING.md

Please provide following information to help code review process a bit
easier:
-->
### Description of PR

`test_bgp_router_id.py` is failing in`main`. It seems to be related to
the sync
https://github.com/nexthop-ai/private-sonic-mgmt/pull/884/changes/cf86c8338b52c0039911fdb19bef0196b827b59d
where we kept internal Nexthop version of `set_router_id_config()` and
`unset_router_id_config()` (which don't pass tbinfo) But accepted the
upstream version of `restart_bgp(duthost, tbinfo)` (which requires
`tbinfo`)

Symptom:
```
            <error message="failed on setup with "TypeError: restart_bgp() missing 1 required positional argument: 'tbinfo'"">duthosts = [<MultiAsicSonicHost blkt156>]
enum_frontend_dut_hostname = 'blkt156'
tbinfo = {'auto_recover': 'True', 'comment': 'SW Lab SONiC Tests', 'conf-name': 'blkt156', 'duts': ['blkt156'], ...}

    @pytest.fixture()
    def router_id_setup_and_teardown(duthosts, enum_frontend_dut_hostname, tbinfo):
        duthost = duthosts[enum_frontend_dut_hostname]
>       set_router_id_config(duthost, CUSTOMIZED_BGP_ROUTER_ID)

duthost    = <MultiAsicSonicHost blkt156>
duthosts   = [<MultiAsicSonicHost blkt156>]
enum_frontend_dut_hostname = 'blkt156'
tbinfo     = {'auto_recover': 'True', 'comment': 'SW Lab SONiC Tests', 'conf-name': 'blkt156', 'duts': ['blkt156'], ...}

bgp/test_bgp_router_id.py:153: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

duthost = <MultiAsicSonicHost blkt156>, router_id = '8.8.8.8'

    def set_router_id_config(duthost, router_id=None):
        if router_id is None:
            raise ValueError("router_id must be provided for configuration")
        # Check if FRR management framework is enabled
        if duthost.get_frr_mgmt_framework_config():
            # no need to restart bgp in UMF mode
            cmd = f'sonic-db-cli CONFIG_DB hset "BGP_GLOBALS|default" "router_id" "{router_id}"'
            duthost.shell(cmd, module_ignore_errors=True)
        else:
            # restart bgp is needed in non-UMF mode
            cmd = f'sonic-db-cli CONFIG_DB hset "DEVICE_METADATA|localhost" "bgp_router_id" "{router_id}"'
            duthost.shell(cmd, module_ignore_errors=True)
>           restart_bgp(duthost)
E           TypeError: restart_bgp() missing 1 required positional argument: 'tbinfo'

cmd        = 'sonic-db-cli CONFIG_DB hset "DEVICE_METADATA|localhost" "bgp_router_id" "8.8.8.8"'
duthost    = <MultiAsicSonicHost blkt156>
router_id  = '8.8.8.8'

bgp/test_bgp_router_id.py:34: TypeError</error>
```



http://qp:8081/qp-testresults?&hwsku=NH-4010-F&days=20&test=tests/bgp/test_bgp_router_id.py


Summary:
Fixes NOS-4921 #done

### Type of change

<!--
- Fill x for your type of change.
- e.g.
- [x] Bug fix
-->

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] New Test case
    - [ ] Skipped for non-supported platforms
- [ ] Test case improvement


### Back port request
- [ ] 202505
- [ ] 202511

### Approach
#### What is the motivation for this PR?

See above description

#### How did you do it?

Pass in `tbinfo` at various places

#### How did you verify/test it?

```
nhtests-run --db-host ${DB_HOST} --testbed ${DUT_NAME} --test-repository sonic --mode run_optimal --test_files tests/bgp/test_bgp_router_id.py
```

<img width="1295" height="453" alt="Screenshot 2026-02-18 at 4 15 37 PM"
src="https://github.com/user-attachments/assets/78077989-6b44-48cc-9126-6a4e5d2000cd"
/>
<img width="1336" height="307" alt="Screenshot 2026-02-18 at 4 19 03 PM"
src="https://github.com/user-attachments/assets/e72b9a26-23c9-4ba1-9329-5098b30b0148"
/>


Test logs:

[NOS-4921.log](https://github.com/user-attachments/files/25402598/NOS-4921.log)

[NOS-4921.xml](https://github.com/user-attachments/files/25402599/NOS-4921.xml)

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation
<!--
(If it's a new feature, new test case)
Did you update documentation/Wiki relevant to your implementation?
Link to the wiki page?
-->