NOS-5874: fix test_generic_hash.py failure of "Expected packet not received" (#1367)
Summary: Fix test_generic_hash.py failure when IP_PROTOCOL hash field
test exercises GRE (protocol 47)
Fixes # (issue)

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] New Test case
    - [ ] Skipped for non-supported platforms
- [ ] Test case improvement

#### Upstream required

- [x] Yes
- [ ] No

#### Upstream requirements (if PR has "Upstream Required" label)

- [x] PR title is free of sensitive information (customer names, product
codenames, internal references)

#### Which release branch to port
- [ ] master
- [ ] 202511
- [x] 202505

### Approach
#### What is the motivation for this PR?

test_generic_hash.py was consistently failing when it landed on the
HASH_FIELD of IP_PROTOCOL (hash field is chosen at random in test case).
When it did, it would error with this failure:

```
hash/test_generic_hash.py::test_ecmp_and_lag_hash[CRC_CCITT-IP_PROTOCOL-ipv4-None-None] 
-------------------------------- live log call ---------------------------------
03/04/2026 17:10:39 ptf_runner.ptf_runner                    L0224 ERROR  | Exception caught while executing case: generic_hash_test.GenericHashTest. Error message: Traceback (most recent call last):
  File "/var/AzDevOps/sonic-mgmt/tests/ptf_runner.py", line 206, in ptf_runner
    result = host.shell(cmd, chdir="/root", module_ignore_errors=module_ignore_errors, module_async=async_mode)
  File "/var/AzDevOps/sonic-mgmt/tests/common/devices/base.py", line 134, in _run
    raise RunAnsibleModuleFail("run module {} failed".format(self.module_name), res)
tests.common.errors.RunAnsibleModuleFail: run module shell failed, Ansible Results =>
failed = True
changed = True
rc = 1
cmd = /usr/local/bin/ptf --test-dir ptftests/py3 generic_hash_test.GenericHashTest --platform-dir ptftests --qlen=20000 --platform remote -t 'router_mac='"'"'e8:e4:9d:10:5e:48'"'"';sending_ports=[4];expected_port_groups=[[0], [1], [2], [3]];hash_field='"'"'IP_PROTOCOL'"'"';vlan_range=[1032, 1060];ethertype_range=[2049, 2304];ipver='"'"'ipv4'"'"';src_ip_range='"'"'8.0.0.0,8.255.255.255'"'"';dst_ip_range='"'"'9.0.0.0,9.255.255.255'"'"';balancing_test_times=480;balancing_range=0.25;ecmp_hash=True;lag_hash=True;is_l2_test=False' --relax --debug info --log-file /tmp/generic_hash_test.GenericHashTest.log --socket-recv-size 16384
start = 2026-04-03 17:10:12.466239
end = 2026-04-03 17:10:39.369557
delta = 0:00:26.903318
msg = non-zero return code
invocation = {'module_args': {'chdir': '/root', '_raw_params': '/usr/local/bin/ptf --test-dir ptftests/py3 generic_hash_test.GenericHashTest --platform-dir ptftests --qlen=20000 --platform remote -t \'router_mac=\'"\'"\'e8:e4:9d:10:5e:48\'"\'"\';sending_ports=[4];expected_port_groups=[[0], [1], [2], [3]];hash_field=\'"\'"\'IP_PROTOCOL\'"\'"\';vlan_range=[1032, 1060];ethertype_range=[2049, 2304];ipver=\'"\'"\'ipv4\'"\'"\';src_ip_range=\'"\'"\'8.0.0.0,8.255.255.255\'"\'"\';dst_ip_range=\'"\'"\'9.0.0.0,9.255.255.255\'"\'"\';balancing_test_times=480;balancing_range=0.25;ecmp_hash=True;lag_hash=True;is_l2_test=False\' --relax --debug info --log-file /tmp/generic_hash_test.GenericHashTest.log --socket-recv-size 16384', '_uses_shell': True, 'warn': False, 'stdin_add_newline': True, 'strip_empty_ends': True, 'argv': None, 'executable': None, 'creates': None, 'removes': None, 'stdin': None}}
_ansible_no_log = None
stdout =
Using packet manipulation module: ptf.packet_scapy

******************************************
ATTENTION: SOME TESTS DID NOT PASS!!!

The following tests failed:
GenericHashTest

******************************************stderr =
generic_hash_test.GenericHashTest ... 17:10:37.608  root      : ERROR   : Traffic wasn't sent successfully, trying again
FAIL

======================================================================
FAIL: generic_hash_test.GenericHashTest
----------------------------------------------------------------------
Traceback (most recent call last):
  File "ptftests/py3/generic_hash_test.py", line 396, in check_ip_route
    port_index, received = testutils.verify_packet_any_port(
  File "/usr/local/lib/python3.9/dist-packages/ptf/testutils.py", line 3442, in verify_packet_any_port
    test.fail(
  File "/usr/lib/python3.9/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: Did not receive expected packet on any of ports [0, 1, 2, 3] for device 0.
========== EXPECTED ==========
Mask:

packet status: OK
packet:
0000  E8 E4 9D 10 5E 48 FE 4C 27 F2 B0 04 08 00 45 00  ....^H.L'.....E.
0010  00 56 00 01 00 00 40 2F 69 79 08 00 00 00 09 00  .V....@/iy......
0020  00 00 04 D2 00 50 00 00 00 00 00 00 00 00 50 02  .....P........P.
0030  20 00 7D 80 00 00 00 01 02 03 04 05 06 07 08 09   .}.............
0040  0A 0B 0C 0D 0E 0F 10 11 12 13 14 15 16 17 18 19  ................
0050  1A 1B 1C 1D 1E 1F 20 21 22 23 24 25 26 27 28 29  ...... !"#$%&'()
0060  2A 2B 2C 2D                                      *+,-

packet's mask:
0000  00 00 00 00 00 00 00 00 00 00 00 00 FF FF FF FF  ................
0010  FF FF FF FF FF FF 00 FF 00 00 FF FF FF FF FF FF  ................
0020  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  ................
0030  FF FF 00 00 FF FF FF FF FF FF FF FF FF FF FF FF  ................
0040  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  ................
0050  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF  ................
0060  FF FF FF FF                                      ....

========== RECEIVED ==========
16 total packets. Displaying most recent 3 packets:
------------------------------
0000  76 C0 E6 07 3D 1D E8 E4 9D 10 5E 48 86 DD 6C 03  v...=.....^H..l.
0010  44 12 00 33 06 01 FC 00 00 00 00 00 00 00 00 00  D..3............
0020  00 00 00 00 00 0D FC 00 00 00 00 00 00 00 00 00  ................
0030  00 00 00 00 00 0E C2 A2 00 B3 6F 24 12 44 76 E6  ..........o$.Dv.
0040  4E E6 80 18 00 92 42 58 00 00 01 01 08 0A C2 DE  N.....BX........
0050  57 0A AA 40 68 D4 FF FF FF FF FF FF FF FF FF FF  W..@h...........
0060  FF FF FF FF FF FF 00 13 04                       .........
------------------------------
0000  2E 91 5C CD 79 BC E8 E4 9D 10 5E 48 86 DD 6C 0D  ..\.y.....^H..l.
0010  77 E5 00 33 06 01 FC 00 00 00 00 00 00 00 00 00  w..3............
0020  00 00 00 00 00 89 FC 00 00 00 00 00 00 00 00 00  ................
0030  00 00 00 00 00 8A 9D 52 00 B3 CF EF 49 2C C7 55  .......R....I,.U
0040  F8 55 80 18 00 7C 29 F4 00 00 01 01 08 0A AB 5D  .U...|)........]
0050  2F 00 5C 68 A1 77 FF FF FF FF FF FF FF FF FF FF  /.\h.w..........
0060  FF FF FF FF FF FF 00 13 04                       .........
------------------------------
0000  A6 DA C4 EA 07 C0 E8 E4 9D 10 5E 48 08 00 45 C0  ..........^H..E.
0010  00 47 63 BB 40 00 01 06 01 2E 0A 00 00 04 0A 00  .Gc.@...........
0020  00 05 8C 94 00 B3 C5 6C 4C B1 A2 1C 36 0E 80 18  .......lL...6...
0030  00 6F 13 AA 00 00 01 01 08 0A B2 63 ED 11 37 A0  .o.........c..7.
0040  FB C7 FF FF FF FF FF FF FF FF FF FF FF FF FF FF  ................
0050  FF FF 00 13 04                                   .....
==============================
```

The PTF expects a packet with IP proto 2F (47), corresponding to GRE,
but does not receive it. Likely, the DUT pipeline (GE XGS) is
interacting with tunneled protocols differently. This specific packet is
just a packet with proto changed to GRE, so it may be detected as
malformed by the parser and dropped.

#### How did you do it?

The goal of this test case is just to evaluate that different IP
protocols are properly hashed out of different paths by ECMP when
hash_field=IP_PROTOCOL, not to evaluate tunneled protocols/GRE
specifically, so we should just skip it.

Already many tunneled protocols are skipped in this list, and in the
older
[hash_test.py](https://github.com/nexthop-ai/sonic-mgmt/blob/master/ansible/roles/test/files/ptftests/py3/hash_test.py#L251),
we do skip GRE. So this change just brings it in line with that.

#### How did you verify/test it?

Without the fix, I verified that the test consistently fails on XGS.
Then adding the patch, the test consistently passes. I specifically
tested only with hash_field = IP_PROTOCOL:

```
> nhtests-run \
--testbed gold414 \
--test-repository sonic \
--mode run_optimal \
--test_files "tests/hash/test_generic_hash.py" \
--test-filter "test_ecmp_and_lag_hash" \
-e='--hash_field=IP_PROTOCOL' \
-e='--algorithm=CRC_CCITT' \
-e='--ip_version=ipv4'

=================================== XPASSES ====================================
_________ test_ecmp_and_lag_hash[CRC_CCITT-IP_PROTOCOL-ipv4-None-None] _________
```

#### Any platform specific information?
TH5

#### Supported testbed topology if it's a new test case?
N/A

### Documentation
N/A